### ISSUE TITLE
tracking domain i ST.nu emagazine app

### ISSUE THREAD

**Issue by BourbonCrow** [lassekongo83/Frellwits-filter-lists#168]
### Förutsättningar

- [X] Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
- [ ] Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
- [ ] Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.

### Beskrivning

kopierarar det jag skrev till hagezi såg den åkte förbi hans lista och gjorde en ctrl+f i din lista och hitta den inte så tänkte lika bra jag reportar den här oxå!, kryssade inte i ubo efter som det är app och detta är mer ett dns relaterad blocking.

Why should these domain(s) be blocked?

this domain leads to a 1x1 pixel transparent gif image so most likely used for tracking + the domain name kinda gave it away

st.nu being the news site and etidning (translated: eMagazine would be their news app) so those 2 should not be blocked just the tracking subdomain

### URL(er) där problemet uppstår.

tracking.etidning.st.nu

### Annonsblockerare och version

adguard for android 4.0

### Webbläsare och version

firefox android beta 1160b5

**Comment by BourbonCrow** [comment]
glömde nämna Sundsvazlls E-Tidning är appen där domänen andvänds som tracking
