### ISSUE TITLE
tracking domain on illustrerad vetenskap

### ISSUE THREAD

**Issue by BourbonCrow** [lassekongo83/Frellwits-filter-lists#169]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
- [X] I've tried to reproduce the issue with uBlock Origin's default settings.

### Description

1x1 tracking pixel related to https://illvet.se/  not sure where it shows up but i keep seeing it in my nextdns logs link to tracking pixel below, i tried blocking it my self and no issue seems to occur

### URL(s) where the issue occurs.

tracking.illvet.se

### Adblocker used and version

ublock 1.50

### Browser name and version

firefox 115.0.2
