### ISSUE TITLE
foodora.se unblocked ad on order tracking page

### ISSUE THREAD

**Issue by wallrik** [lassekongo83/Frellwits-filter-lists#190]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I use no other ad blockers or privacy blocking tools/extensions other than my preferred one. (To rule out invalid issues it's important to use only one blocker.)
- [X] I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
- [X] I've tried to reproduce the issue with uBlock Origin's default settings.

### Description

Foodora displays ads on their order tracking page that the generic EasyList `-ad`-style rules don't seem to hit. Unfortunately, I have not found any way to reproduce this without actually having an account and having at least one previous order.

For that reason, I've included a screenshot with the inspect panel open. My suggested rule would be something like `foodora.se##div[data-testid="partnership-ads"]` unless doing it by class names is preferred.

### URL(s) where the issue occurs.

`https://www.foodora.se/order-tracking/<ordernumber>`

### Screenshot(s)

Inspect panel open.
![Inspect panel open](https://github.com/lassekongo83/Frellwits-filter-lists/assets/10890923/1bf26eee-3e9b-43b8-a9b0-1636889f39aa)

With suggested rule (ads get successfully removed)
![With ads hidden](https://github.com/lassekongo83/Frellwits-filter-lists/assets/10890923/6a9e5569-96c4-4f28-8cd8-8349a3fd9f8c)

### Adblocker used and version

uBlock Origin 1.56.0

### Browser name and version

Firefox 123.0

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 119850
 cosmetic: 122266
 scriptlet: 27781
 html: 2056
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  easylist-annoyances: 4381-97, 1d.15h.55m
  easylist-chat: 182-0, 6d.18h.39m
  fanboy-cookiemonster: 66143-16199, 4d.18h.22m
  easylist-newsletters: 7010-13, 1d.15h.55m
  easylist-notifications: 2947-4, 1d.15h.55m
  fanboy-social: 16183-30, 4d.18h.23m
  ublock-annoyances: 6757-986, 1h.38m Δ
  SWE-1: 4652-18, 2h.38m Δ
  ublock-cookies-easylist: 956-0, 1d.15h.54m
 default:
  user-filters: 0-0, never
  ublock-filters: 37596-125, 1h.38m Δ
  ublock-badware: 8006-14, 1h.38m Δ
  ublock-privacy: 740-0, 1h.38m Δ
  ublock-unbreak: 2280-2, 1h.38m Δ
  ublock-quick-fixes: 123-0, 1h.38m Δ
  easylist: 81749-292, 1h.38m Δ
  easyprivacy: 50273-161, 1h.38m Δ
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 164 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
```
</details>
